name: Allure Report Pipeline
on:
  push:
    branches:
      - feature-chathura

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99
      CHROME_BIN: /usr/bin/google-chrome

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Start API JAR Server
      - name: Start API JAR Server
        run: |
          nohup java -jar API/env/demo-0.0.1-SNAPSHOT.jar &
          sleep 5 # Give time for the server to start 

      # Step 12: Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn install -DskipTests

      # Step 13: Run API tests and generate Allure results
      - name: Run API tests and generate Allure results
        run: |
          mvn test -Dtest=runner.RunCucumberTest \
            -Dallure.results.directory=target/allure-results
        continue-on-error: true

      # Step 16: Generate Combined Allure Report
      - name: Generate Combined Allure Report
        run: |
          npm install -g allure-commandline --force
          allure generate target/allure-results --clean -o target/allure-report

      # Step 9: Deploy Combined Allure Report to GitHub Pages
      - name: Deploy Combined Allure Report to GitHub Pages
        if: success() && github.ref == 'refs/heads/feature-chathura'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/allure-report
          target-folder: report
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}