name: Allure Report Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99
      CHROME_BIN: /usr/bin/google-chrome

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Start API JAR Server
        run: |
          nohup java -jar env/demo-0.0.1-SNAPSHOT.jar &
          sleep 5 # Give time for the server to start 


      - name: Install Maven dependencies
        run: mvn install -DskipTests


      - name: Run API tests and generate Allure results
        run: |
          mvn test -Dtest=runner.RunCucumberTest \
            -Dallure.results.directory=target/allure-results
        continue-on-error: true


      - name: Generate Combined Allure Report
        run: |
          npm install -g allure-commandline --force
          allure generate target/allure-results --clean -o target/allure-report


      - name: Deploy Combined Allure Report to GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/allure-report
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}